steps:

- id: "Instalando o desafio-ci..."
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'desafio-ci']
  env: ['GOPATH=.']

- id: "Testando o desafio-ci"
  name: "gcr.io/cloud-builders/go"
  args: ['test', '-v','./...']
  env: ["GOPATH=."]

- id: "Criando build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-ci', '.']

images:
  - 'gcr.io/$PROJECT_ID/desafio-ci'